services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-library
    ports:
      - "8088:8088"
    networks:
      - music-network
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: music-library_db
    ports:
      - "5431:5432"
    networks:
      - music-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
  music-api:
    build: ./music-api 
    container_name: music-api
    ports:
      - "8081:8080"
    networks:
      - music-network
    depends_on:
      - db
  migrate:
    image: migrate/migrate:latest
    container_name: music-library_migrate
    networks:
      - music-network
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable", "up"]

volumes:
  postgres_data:

networks:
  music-network: